# permissions for end users to edit schemaloggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: schemalogger-editor-role
rules:
- apiGroups:
  - broadcast.broadcast.logger
  resources:
  - schemaloggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - broadcast.broadcast.logger
  resources:
  - schemaloggers/status
  verbs:
  - get
